let
    Source = Folder.Files("C:\Users\mvvb8\Documents\Coursera\bike data"),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "202301-divvy-tripdata.csv" or [Name] = "202302-divvy-tripdata.csv" or [Name] = "202303-divvy-tripdata.csv" or [Name] = "202304-divvy-tripdata.csv" or [Name] = "202305-divvy-tripdata.csv" or [Name] = "202306-divvy-tripdata.csv" or [Name] = "202307-divvy-tripdata.csv" or [Name] = "202308-divvy-tripdata.csv" or [Name] = "202309-divvy-tripdata.csv" or [Name] = "202310-divvy-tripdata.csv" or [Name] = "202311-divvy-tripdata.csv" or [Name] = "202312-divvy-tripdata.csv")),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Name", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Removed Columns", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"ride_id", type text}, {"rideable_type", type text}, {"started_at", type datetime}, {"ended_at", type datetime}, {"start_station_name", type text}, {"start_station_id", type text}, {"end_station_name", type text}, {"end_station_id", type text}, {"start_lat", type number}, {"start_lng", type number}, {"end_lat", type number}, {"end_lng", type number}, {"member_casual", type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each ([start_station_name] <> "")),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"ride_id"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns1", "started_at", "started_at - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"started_at - Copy", "started_date"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"started_date", type date}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Changed Type1", "ended_at", "ended_at - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"ended_at - Copy", "ended_date"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"ended_date", type date}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type2",{"started_date", "ended_date", "start_station_name", "start_station_id", "end_station_name", "end_station_id", "start_lat", "start_lng", "end_lat", "end_lng"}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Removed Columns2", "started_at", "started_at - Copy"),
    #"Extracted Month Name" = Table.TransformColumns(#"Duplicated Column2", {{"started_at - Copy", each Date.MonthName(_), type text}}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Extracted Month Name", "started_at", "started_at - Copy.1"),
    #"Extracted Hour" = Table.TransformColumns(#"Duplicated Column3",{{"started_at - Copy.1", Time.Hour, Int64.Type}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Extracted Hour",{"started_at - Copy.1"}),
    #"Filtered Rows2" = Table.SelectRows(#"Removed Columns3", each true),
    #"Renamed Columns2" = Table.RenameColumns(#"Filtered Rows2",{{"started_at - Copy", "month"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "trip_duration", each [ended_at]-[started_at]),
    #"Duplicated Column4" = Table.DuplicateColumn(#"Added Custom", "trip_duration", "trip_duration - Copy"),
    #"Extracted Minutes" = Table.TransformColumns(#"Duplicated Column4",{{"trip_duration - Copy", Duration.Minutes, Int64.Type}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Extracted Minutes",{{"trip_duration - Copy", "trip_duration.minutes"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"trip_duration.minutes", type number}}),
    #"Duplicated Column5" = Table.DuplicateColumn(#"Changed Type3", "trip_duration", "trip_duration - Copy"),
    #"Added Custom1" = Table.AddColumn(#"Duplicated Column5", "total_trip.minutes", each Duration.TotalMinutes([ended_at]-[started_at])),
    #"Removed Columns4" = Table.RemoveColumns(#"Added Custom1",{"trip_duration - Copy"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns4",{"rideable_type", "member_casual", "started_at", "ended_at", "month", "trip_duration", "trip_duration.minutes", "total_trip.minutes"}),
    #"Filtered Rows3" = Table.SelectRows(#"Reordered Columns", each [total_trip.minutes] >= 1),
    #"Duplicated Column6" = Table.DuplicateColumn(#"Filtered Rows3", "started_at", "started_at - Copy"),
    #"Calculated Quarter" = Table.TransformColumns(#"Duplicated Column6",{{"started_at - Copy", Date.QuarterOfYear, Int64.Type}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Calculated Quarter",{{"started_at - Copy", "quarter"}}),
    #"Filtered Rows4" = Table.SelectRows(#"Renamed Columns4", each ([quarter] = 1 or [quarter] = 4)),
    #"Removed Columns5" = Table.RemoveColumns(#"Filtered Rows4",{"trip_duration.minutes"}),
    #"Duplicated Column7" = Table.DuplicateColumn(#"Removed Columns5", "started_at", "started_at - Copy"),
    #"Renamed Columns5" = Table.RenameColumns(#"Duplicated Column7",{{"started_at - Copy", "weekday"}}),
    #"Extracted Day Name" = Table.TransformColumns(#"Renamed Columns5", {{"weekday", each Date.DayOfWeekName(_), type text}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Extracted Day Name",{"rideable_type", "member_casual", "started_at", "ended_at", "month", "weekday", "trip_duration", "total_trip.minutes", "quarter"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Reordered Columns1",{"started_at", "ended_at", "trip_duration"})
in
    #"Removed Columns6"
